import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Page Posts Mini Blog",
  description: "Generated by create next app",
};

export default function PostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex gap-4">
      <aside className="w-1/4 p-4 border-r">
        <h2 className="font-bold mb-2">Sidebar</h2>
        <ul>
          <li>
            <Link href="/posts">All Posts</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
        </ul>
      </aside>
      <section className="flex-1 p-4">{children}</section>
    </div>
  );
}
