import SiderBar from "@/components/SiderBar";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Page Posts Mini Blog",
  description: "Generated by create next app",
};

export default function PostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex gap-4">
      <SiderBar />
      <section className="flex-1 p-4">{children}</section>
    </div>
  );
}
